name: ci

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2

    - name: install build tools
      run: |
        apt update -y
        apt install -y rake tree

    - name: build and run tests
      run: |
        tree
        rake
